/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme.ts
 * Command: astryx theme build theme.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/**
 * razbor theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { razborTheme } from './razbor';
 *   import './razbor.css';
 */
export const razborTheme = {
  name: 'razbor',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#2255CD, #B4C4FF)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #003077)",
    "--color-neutral": "light-dark(#1B1B1F1A, #E1E2E833)",
    "--color-background-surface": "light-dark(#FFFFFF, #1F1F22)",
    "--color-background-body": "light-dark(#EFEFEC, #111112)",
    "--color-overlay": "light-dark(#1B1B1F66, #1B1B1F99)",
    "--color-overlay-hover": "light-dark(#1B1B1F0D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1B1B1F1A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#1B1B1F0D, #1B1B1F80)",
    "--color-text-primary": "light-dark(#000000, #FBFCFF)",
    "--color-text-secondary": "light-dark(#303038, #C4C6D1)",
    "--color-text-disabled": "light-dark(#90909A, #5C5E68)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#000000, #FBFCFF)",
    "--color-icon-secondary": "light-dark(#303038, #C4C6D1)",
    "--color-icon-disabled": "light-dark(#90909A, #5C5E68)",
    "--color-background-card": "light-dark(#FCFCFF, #1B1B1F)",
    "--color-background-popover": "light-dark(#FCFCFF, #2F3035)",
    "--color-background-inverted": "light-dark(#1B1B1F, #FBFCFF)",
    "--color-border": "light-dark(#1B1B1F33, #EFF0F633)",
    "--color-border-emphasized": "light-dark(#777680, #757781)",
    "--color-skeleton": "light-dark(#ABAAB5, #444650)",
    "--color-track": "light-dark(#ABAAB5, #444650)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.5625rem",
    "--font-size-3xs": "0.625rem",
    "--font-size-2xs": "0.6875rem",
    "--font-size-xs": "0.8125rem",
    "--font-size-sm": "0.875rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.25rem",
    "--font-size-2xl": "1.4375rem",
    "--font-size-3xl": "1.625rem",
    "--font-size-4xl": "1.8125rem",
    "--font-size-5xl": "2rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.3913",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.4",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.4286",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.5385",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4286",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.25",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.3793",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.3846",
    "--radius-none": "0px",
    "--radius-inner": "3px",
    "--radius-element": "6px",
    "--radius-container": "9px",
    "--radius-page": "21px",
    "--radius-chat": "21px",
    "--radius-full": "9999px",
    "--duration-fast-min": "90ms",
    "--duration-fast": "120ms",
    "--duration-fast-max": "160ms",
    "--duration-medium-min": "210ms",
    "--duration-medium": "280ms",
    "--duration-medium-max": "375ms",
    "--duration-slow-min": "450ms",
    "--duration-slow": "600ms",
    "--duration-slow-max": "800ms",
    "--font-family-body": "Manrope, -apple-system, system-ui, sans-serif",
    "--font-family-heading": "Unbounded, -apple-system, system-ui, sans-serif",
    "--font-family-code": "\"JetBrains Mono\", \"SF Mono\", ui-monospace, monospace",
    "--focus-outline-color": "var(--color-accent)"
  },
  localTokens: {
    "--metric-resistance": "light-dark(#BE3C28, #E8654F)",
    "--metric-trust": "light-dark(#16785B, #49C19A)",
    "--metric-adapt": "light-dark(#5259D4, #8B93F5)",
    "--metric-insight": "light-dark(#8F6211, #E0AB52)"
  },
  __localTokenOwners: {
    "--metric-resistance": "razbor",
    "--metric-trust": "razbor",
    "--metric-adapt": "razbor",
    "--metric-insight": "razbor"
  },
  __localTokenLineage: ["razbor"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 16,
        "ratio": 1.125
      },
      "body": {
        "family": "Manrope",
        "fallbacks": "-apple-system, system-ui, sans-serif"
      },
      "heading": {
        "family": "Unbounded",
        "fallbacks": "-apple-system, system-ui, sans-serif",
        "weight": "semibold",
        "weights": {
          "1": "bold",
          "2": "bold"
        }
      },
      "code": {
        "family": "JetBrains Mono",
        "fallbacks": "\"SF Mono\", ui-monospace, monospace"
      }
    },
    "color": {
      "accent": [
        "#2456CE",
        "#6E9BFF"
      ],
      "neutralStyle": "neutral",
      "contrast": "high"
    },
    "radius": {
      "base": 4,
      "multiplier": 0.75
    },
    "motion": {
      "fast": 120,
      "medium": 280,
      "slow": 600,
      "ratio": 0.75
    }
  },

};
